name: Tests
on: [push, pull_request]

jobs:
    tox:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python_version:
            - "3.8"
          tox_env:
            - py
            - style
            - docs
            - postgres
          include:
            - tox_env: py
              friendly_name: Tests
            - tox_env: style
              friendly_name: Style
            - tox_env: docs
              friendly_name: Docs
            - tox_env: postgres
              friendly_name: Postgres
        fail-fast: false
      name: Tox - ${{ matrix.friendly_name }}
      steps:
        - uses: actions/checkout@v2
        - uses: harmon758/postgresql-action@v1
          with:
            postgresql version: "10"
            postgres db: red_db
            postgres user: postgres
            posgres password: postgres
          if: matrix.tox_env == "postgres"
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python_version }}
        - name: Install tox
          run: |
            python -m pip install --upgrade pip
            pip install tox
        - name: Tox test
          env:
            TOXENV: ${{ matrix.tox_env }}
            PGDATABASE: red_db
            PGUSER: postgres
            PGPASSWORD: postgres
          run: tox
